### ISSUE TITLE
ERR command 'mesonbuild.targets-refresh' not found

### ISSUE THREAD

**Issue by TheAifam5** [asabil/vscode-meson#7]
```
workbench.main.js:238 [Extension Host] stack trace: Error: command 'mesonbuild.targets-refresh' not found
    at Proxy._tryExecuteCommand (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:3034:836)
    at r.then.i (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:3034:717)
    at process._tickCallback (internal/process/next_tick.js:68:7)
t.log @ workbench.main.js:238
workbench.main.js:1406   ERR command 'mesonbuild.targets-refresh' not found: Error: command 'mesonbuild.targets-refresh' not found
    at Proxy._tryExecuteCommand (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:3034:836)
    at r.then.i (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:3034:717)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by Ongy** [comment]
This has been fixed for a couple months and the version has been released I think. Should this be closed?
